services:
  db:
    image: mongo:jammy
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
    mongo_data: